export const prefixList = [
  { title: "j j", definition: "- j" },
  { title: "j-", definition: "- j-pop" },
  { title: "ja", definition: "jab - jazzy" },
  { title: "je", definition: "jealous - jews" },
  { title: "jf", definition: "jfk - jfk" },
  { title: "jh", definition: "jhansi - jhelum" },
  { title: "ji", definition: "ji - jive" },
  { title: "jl", definition: "jl - jl" },
  { title: "jo", definition: "jo - joysticks" },
  { title: "jp", definition: "jp - jpeg" },
  { title: "jr", definition: "jr - jr" },
  { title: "js", definition: "js - json" },
  { title: "ju", definition: "juan - juxtaposition" },
  { title: "jv", definition: "jvm - jvm" },
  { title: "jy", definition: "jyutping - jyutping" },
];

export const wordsList = [
  "according",
  "age",
  "air",
  "april",
  "are",
  "area",
  "average",
  "being",
  "book",
  "can",
  "census",
  "church",
  "city",
  "control",
  "county",
  "density",
  "due",
  "end",
  "even",
  "family",
  "film",
  "first",
  "following",
  "form",
  "former",
  "four",
  "general",
  "government",
  "great",
  "group",
  "have",
  "high",
  "history",
  "home",
  "house",
  "including",
  "income",
  "international",
  "journal",
  "king",
  "last",
  "life",
  "list",
  "living",
  "local",
  "main",
  "major",
  "may",
  "median",
  "military",
  "modern",
  "most",
  "much",
  "music",
  "name",
  "national",
  "news",
  "now",
  "number",
  "one",
  "order",
  "original",
  "over",
  "own",
  "part",
  "party",
  "place",
  "political",
  "population",
  "public",
  "river",
  "school",
  "second",
  "series",
  "set",
  "several",
  "she",
  "size",
  "small",
  "some",
  "state",
  "such",
  "system",
  "then",
  "there",
  "those",
  "three",
  "time",
  "total",
  "town",
  "two",
  "use",
  "war",
  "web",
  "well",
  "while",
  "will",
  "work",
  "world",
  "year",
];
