export const prefixList = [
  { title: "j j", definition: "- j" },
  { title: "j-", definition: "- j-pop" },
  { title: "ja", definition: "jab - jazzy" },
  { title: "je", definition: "jealous - jews" },
  { title: "jf", definition: "jfk - jfk" },
  { title: "jh", definition: "jhansi - jhelum" },
  { title: "ji", definition: "ji - jive" },
  { title: "jl", definition: "jl - jl" },
  { title: "jo", definition: "jo - joysticks" },
  { title: "jp", definition: "jp - jpeg" },
  { title: "jr", definition: "jr - jr" },
  { title: "js", definition: "js - json" },
  { title: "ju", definition: "juan - juxtaposition" },
  { title: "jv", definition: "jvm - jvm" },
  { title: "jy", definition: "jyutping - jyutping" },
];

export const wordsList = [
  "according",
  "age",
  "air",
  "april",
  "are",
  "area",
  "average",
  "being",
  "book",
  "can",
  "census",
  "church",
  "city",
  "control",
  "county",
  "density",
  "due",
  "end",
  "even",
  "family",
  "film",
  "first",
  "following",
  "form",
  "former",
  "four",
  "general",
  "government",
  "great",
  "group",
  "have",
  "high",
  "history",
  "home",
  "house",
  "including",
  "income",
  "international",
  "journal",
  "king",
  "last",
  "life",
  "list",
  "living",
  "local",
  "main",
  "major",
  "may",
  "median",
  "military",
  "modern",
  "most",
  "much",
  "music",
  "name",
  "national",
  "news",
  "now",
  "number",
  "one",
  "order",
  "original",
  "over",
  "own",
  "part",
  "party",
  "place",
  "political",
  "population",
  "public",
  "river",
  "school",
  "second",
  "series",
  "set",
  "several",
  "she",
  "size",
  "small",
  "some",
  "state",
  "such",
  "system",
  "then",
  "there",
  "those",
  "three",
  "time",
  "total",
  "town",
  "two",
  "use",
  "war",
  "web",
  "well",
  "while",
  "will",
  "work",
  "world",
  "year",
];

export const wordDetails = {
  title: "air",
  transcription: "æə",
  definitions: [
    {
      typeEn: "noun",
      typeUz: "ot",
      meaning: "havo",
      plural: "airs",
      others: [
        {
          meaning: "havo",
          examples: [
            {
              phrase: "air conditioning system",
              translation: "havo konditsionerlash tizimi",
            },
            {
              phrase: "relative air humidity",
              translation: "havo namligining nisbati",
            },
            {
              phrase: "ambient air temperature",
              translation: "atrof muhit havo harorati",
            },
            {
              phrase: "atmospheric air pollution",
              translation: "atmosfera havosining ifloslanishi",
            },
            {
              phrase: "compressed air consumption",
              translation: "siqilgan havoni iste'mol qilish",
            },
          ],
        },
        {
          meaning: "shabada",
          examples: [{ phrase: "evening air", translation: "kechki shabada" }],
        },
        {
          meaning: "shamol",
        },
      ],
      synonymList: [
        "atmosphere",
        "aeroplane",
        "aerosphere",
        "aether",
        "aircraft",
        "airwaves",
        "ambiance",
        "aura",
        "aviation",
        "broadcast",
        "craft",
        "ester",
        "ether",
        "jet",
        "midair",
      ],
      examples: [
        {
          phrase: "air conditioning system",
          translation: "havo konditsionerlash tizimi",
        },
        {
          phrase: "relative air humidity",
          translation: "havo namligining nisbati",
        },
        {
          phrase: "ambient air temperature",
          translation: "atrof muhit havo harorati",
        },
        {
          phrase: "atmospheric air pollution",
          translation: "atmosfera havosining ifloslanishi",
        },
        {
          phrase: "compressed air consumption",
          translation: "siqilgan havoni iste'mol qilish",
        },
      ],
    },
    {
      typeEn: "verb",
      typeUz: "fe'l",
      meaning: "efirga uzatmoq, havo berish",
      others: [
        {
          meaning: "efirga uzatmoq",
          examples: [
            {
              phrase: "The show will air tomorrow.",
              translation: "Ko'rsatuv ertaga efirga uzatiladi.",
            },
            {
              phrase: "They aired the debate live.",
              translation: "Ular munozarani jonli efirda ko'rsatishdi.",
            },
          ],
        },
        {
          meaning: "havo berish, havalandirmoq",
          examples: [
            {
              phrase: "I need to air the room.",
              translation: "Xonani havalandirishim kerak.",
            },
            {
              phrase: "The laundry was aired outside.",
              translation: "Kirlar tashqarida havalandirildi.",
            },
          ],
        },
      ],
      synonymList: [
        "broadcast",
        "ventilate",
        "expose",
        "publicize",
        "announce",
        "transmit",
        "disclose",
        "reveal",
        "make public",
      ],
      examples: [
        {
          phrase: "The show will air tomorrow.",
          translation: "Ko'rsatuv ertaga efirga uzatiladi.",
        },
        {
          phrase: "I need to air the room.",
          translation: "Xonani havalandirishim kerak.",
        },
        {
          phrase: "They aired the debate live.",
          translation: "Ular munozarani jonli efirda ko'rsatishdi.",
        },
      ],
    },
  ],
  usageFrequency: 443,
  exampleSentences: [
    {
      sentence: "Without air and water, nothing could live.",
      translation: "Havo va suvsiz hech narsa yashay olmaydi.",
    },
    {
      sentence: "The air felt a little cold.",
      translation: "Havo biroz sovuq edi.",
    },
    {
      sentence: "Flowers and trees need clean air and fresh water.",
      translation: "Gullar va daraxtlarga toza havo va yangi suv kerak.",
    },
    {
      sentence: "I put on an air of interest.",
      translation: "Men qiziqish ko'rsatdim.",
    },
    {
      sentence: "It's very warm. Shall I turn on the air conditioner?",
      translation: "Juda issiq. Konditsionerni yoqaymi?",
    },
    {
      sentence: "The air conditioner doesn't work.",
      translation: "Konditsioner ishlamayapti.",
    },
    {
      sentence: "My house doesn't have an air conditioner.",
      translation: "Mening uyimda konditsioner yo'q.",
    },
    {
      sentence: "The air here is awful.",
      translation: "Bu yerdagi havo dahshatli.",
    },
  ],
  verbForms: {
    presentSimple: {
      firstPersonSingular: "I air",
      secondPersonSingular: "You air",
      thirdPersonSingular: "He/She/It airs",
      firstPersonPlural: "We air",
      secondPersonPlural: "You air",
      thirdPersonPlural: "They air",
    },
    pastSimple: {
      firstPersonSingular: "I aired",
      secondPersonSingular: "You aired",
      thirdPersonSingular: "He/She/It aired",
      firstPersonPlural: "We aired",
      secondPersonPlural: "You aired",
      thirdPersonPlural: "They aired",
    },
    futureSimple: {
      firstPersonSingular: "I will air",
      secondPersonSingular: "You will air",
      thirdPersonSingular: "He/She/It will air",
      firstPersonPlural: "We will air",
      secondPersonPlural: "You will air",
      thirdPersonPlural: "They will air",
    },
    presentContinuous: {
      firstPersonSingular: "I am airing",
      secondPersonSingular: "You are airing",
      thirdPersonSingular: "He/She/It is airing",
      firstPersonPlural: "We are airing",
      secondPersonPlural: "You are airing",
      thirdPersonPlural: "They are airing",
    },
    pastContinuous: {
      firstPersonSingular: "I was airing",
      secondPersonSingular: "You were airing",
      thirdPersonSingular: "He/She/It was airing",
      firstPersonPlural: "We were airing",
      secondPersonPlural: "You were airing",
      thirdPersonPlural: "They were airing",
    },
    futureContinuous: {
      firstPersonSingular: "I will be airing",
      secondPersonSingular: "You will be airing",
      thirdPersonSingular: "He/She/It will be airing",
      firstPersonPlural: "We will be airing",
      secondPersonPlural: "You will be airing",
      thirdPersonPlural: "They will be airing",
    },
    presentPerfect: {
      firstPersonSingular: "I have aired",
      secondPersonSingular: "You have aired",
      thirdPersonSingular: "He/She/It has aired",
      firstPersonPlural: "We have aired",
      secondPersonPlural: "You have aired",
      thirdPersonPlural: "They have aired",
    },
    pastPerfect: {
      firstPersonSingular: "I had aired",
      secondPersonSingular: "You had aired",
      thirdPersonSingular: "He/She/It had aired",
      firstPersonPlural: "We had aired",
      secondPersonPlural: "You had aired",
      thirdPersonPlural: "They had aired",
    },
    futurePerfect: {
      firstPersonSingular: "I will have aired",
      secondPersonSingular: "You will have aired",
      thirdPersonSingular: "He/She/It will have aired",
      firstPersonPlural: "We will have aired",
      secondPersonPlural: "You will have aired",
      thirdPersonPlural: "They will have aired",
    },
  },
  anagrams: ["ira"],
};
